apiVersion: v1
kind: Namespace
metadata:
  name: nxs-operators

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: nxs-k8s-ns-access-operator
  namespace: nxs-operators

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nxs-k8s-ns-access-operator
  namespace: nxs-operators
  labels:
    k8s-app: nxs-k8s-ns-access-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: nxs-k8s-ns-access-operator
    spec:
      serviceAccountName: nxs-k8s-ns-access-operator
      containers:
      - name: nxs-k8s-ns-access-operator
        image: nixyslab/nxs-k8s-ns-access-operator:latest
        imagePullPolicy: Always
        env:
        - name: CLUSTER_ROLE_NAME
          value: "deployer"
