apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ns-creator
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  - batch
  resources:
  - namespaces
  verbs:
  - get
  - list
  - create
